"""rename address

Revision ID: f449a2a511f6
Revises: 5d67c5fc2d61
Create Date: 2024-10-03 17:59:42.382250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f449a2a511f6'
down_revision = '5d67c5fc2d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
    # op.drop_column('departments', 'address')
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    # op.drop_column('departments', 'location')
     op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
